{% set name = "dynesty" %}
{% set version = "2.1.4" %}
{% set sha256 = "cd98cfded1af86487b76dba2bd89824c803f1e0c451fcb14a0b208c5ca1a8004" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - matplotlib-base

test:
  imports:
    - dynesty

about:
  home: https://github.com/joshspeagle/dynesty
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A dynamic nested sampling package for computing Bayesian posteriors and evidences.

  description: |
    dynesty is a dynamic nested sampling package for computing Bayesian posteriors and evidences. Pure Python.
  doc_url: http://dynesty.readthedocs.io/
  dev_url: https://github.com/joshspeagle/dynesty

extra:
  recipe-maintainers:
    - guillochon
    - pkgw
    - joshspeagle
