{% set name = "dynesty" %}
{% set version = "3.0.0" %}
{% set sha256 = "806c83b21904cf7df73c2478a9e0e8a2b7d811cd0d613109f3f810a7111d12b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - matplotlib-base

test:
  requires:
    - python {{ python_min }}
  imports:
    - dynesty

about:
  home: https://github.com/joshspeagle/dynesty
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A dynamic nested sampling package for computing Bayesian posteriors and evidences.

  description: |
    dynesty is a dynamic nested sampling package for computing Bayesian posteriors and evidences. Pure Python.
  doc_url: http://dynesty.readthedocs.io/
  dev_url: https://github.com/joshspeagle/dynesty

extra:
  recipe-maintainers:
    - guillochon
    - pkgw
    - joshspeagle
