travis:
  secure:
    BINSTAR_TOKEN: EIKRG0ZXtPMYUudQTApP+a8xc88oIiqfXItiqdoNZH+llgHfApe/EF2L+OIK9wdhCQ0pVVes6KW0ycvCibvgd/P11GGWrw/cpd8q6+6//DEVwy98wQY1R7xUVc8eVkdWrbVqIXCmJhW76CaBCOD2RP3KXlqgG5uqivwiFNUOoeDd8GaGws2Yn61ykgAcGglH1D1ijvkD8qq6SDyXlQnsqSuMDTnSXvcLwmEQpkInVcdLRSIDxj1u0R/kLrrKuAU3AfUpLhcxnV+8wp0Y7VQXUS/B0EQb12uvCumYX3EutsFdocSoOyfkRl/sNoCgCsFLCMdmBiENGgMKlfhH9ngVwMxaoTEi3TUOYYbTivTO6NfAVs0YXsB3S29onEMcIRNE7fFFB3EFl9luhQsB/EI9L3PewBJ7ttzfBNIIzkZz0eczH6+129Jw18h7lHz37RRXdkUZVi4M9wGIN91S5gD4+v+5RgIJorUYjHNns+CjGVGtjciabYSakj7hB6BTmjJyC7PXtaesBFCe4XiHOZfVgWkc3nwMBiMwAr/nnb+XL7yWSM6Tdjgx5URMcnpHBE6viOlRA9Unh1P+1N2EN7hHDBS5x4xZBgZb0eXuR7CheBF6QVrp3mhAW6nV/SroUD+c4FZsXWw90Aasw14Qu8PkWjsFKkx+qJyrtPVAvO82ANw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
