travis:
  secure:
    BINSTAR_TOKEN: dag3Qb0Iejbnpez6ltJZjmU/YiuEVuhgsh0etxCmtf7YZ8nM3datG4VuyjRwOr1lsILoV1HsiWK9EBVq07n8Ou+v9n07DrB9g4kWYUhj4B/IdVrpCmsFkgYLy7L5s/fsoyp0AU2wvEIoT1oLQ6a6rY8xEuf+QPgEvlAgFaAVHrIJHZzUXxKxPKHv+iyigpXKN0XrjDVRH7Qal7J00xw1wqi4FhWQpVaVcTzilVNDc/KiUXdiWoDOS07HgKRA0vavjHN2mN7wWcIk0etrsuicYkrV8Kof+NgngHW1uCPtr/bhUIJMwtptE5c/2rpmDwFj5D3pq8XoqfBLB6vu3oTY2X9PPmC1BBB3/pmGagAk0TOKsFb7uKe6iW/ke9Wqx3VCKZeRlqe+NhOymnVXidd7ZTYBFL6ftiN+GEBwhO4GGFaeKqhFrbtflqlsYXZuIZk/dxZBmWmAoiFQadgGpXAwC+GD+Gh1KQD8oyd414hsv8G2THQYWmc6FjYhzdXTWLXDCmnE2UjiOZAqj34pGPFqf9yu1pH+FMQONHbIFEB2E0rkXzl9vGVFcGiPlzSKhznWMg88lkObgXtH2TdkcUWj3804CRjJWsVvaMmTGVlHTS3cGBhdHtdqVbWconLIWsqQX17vk1+XIFMU/3PZW4GQOBzuaz1nN7dvQQKC8NCgSYQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
