travis:
  secure:
    BINSTAR_TOKEN: o9qOQcNmJDX0ZirtdrQXf7Jt032jXTM4Mur/69g9bG5y+qbXqcUGanFKpdZNLfAfnx0FMRyoXUhiTP3ylt2wDMwRPqOssRRyj0U531IJiLh/+XfOy+Ba7Z/kVilBDoKHhLG8NeGRv8blO6DqVxoAXvtK87kvyagPSxc33VwnVg/cshwhV55INehOtYUQnBW9Zdb4vQlgME+RrLq9ByiEXwKZe3cSPe1X9ZeV0Dm9KSmFvpz0Jm/3uxiOPPIpgVBpGk8KJRsz3STJK+BACdeyUdWvov3lD7V3ArqU6mXNB1xO99gI2tLWuQQeT07HxNK/6Z5R+QlcgJAf5eHAfxh5we2GAYeNybrwTp0K6kgcl2YHhezhDdWezrIFChGmBvYsCnUSqQB+5rL1MNWDQDQBbZEyzngA/tEptxI4szQiib1EejO4dxlUZ/g7qqORp5bU7QRYkNYoTL4OSDSgQgcURgBzrwaRCeObosu2LXKi2lZiX1BhVNDfG8hJOz3OE/MltEye9IqQU/VZd34jsw/PNY2rvGxZwfOsjE+A/9lwisVbRkeKU7T8UWpT7t8rh9sxgi7oyZy/CzbrqS2tOKxGOMysnCsDYww70N+AKNGe85LRT7hJ0fk7iWE1T4pMuH+ttO9BkQCcrRZ1d5u8AHvqZ6f1tiJhX6ZKHPPD9YqV/hg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
